# ===============================================================================
# APP ROUTES
# -------------------------------------------------------------------------------
arii_JOE_index:
    path: /
    defaults: { _controller: AriiJOEBundle:Default:index }

json_JOE_ribbon:
    pattern:  /ribbon.json
    defaults: { _controller: AriiJOEBundle:Default:ribbon }

js_JOE_routes:
    pattern: /js/routes.js
    defaults: { _controller: AriiJOEBundle:Default:routes }

xml_JOE_menu:
    pattern:  /menu.xml
    defaults: { _controller: AriiJOEBundle:Default:menu }

arii_JOE_readme:
    pattern:  /
    defaults: { _controller: AriiJOEBundle:Default:readme }

# ===============================================================================
# API ROUTES
# -------------------------------------------------------------------------------
arii_JOE_api_create:
    pattern: /api/{target}/create
    methods: [POST]
    defaults: { _controller: AriiJOEBundle:API:create }

arii_JOE_api_update:
    pattern: /api/{target}/update/{id}
    methods: [POST]
    defaults: { _controller: AriiJOEBundle:API:update }

arii_JOE_api_remove:
    pattern: /api/{target}/remove/{id}
    defaults: { _controller: AriiJOEBundle:API:remove }

arii_JOE_api_xml:
    pattern: /api/{target}/xml/{id}
    defaults: { _controller: AriiJOEBundle:API:xml }

arii_JOE_api_json:
    pattern: /api/{target}/json/{id}
    methods: [POST]
    defaults: { _controller: AriiJOEBundle:API:json }

arii_JOE_api_list:
    pattern: /api/{target}/list
    methods: [POST]
    defaults: { _controller: AriiJOEBundle:API:list }
